<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
﻿//// <auto-generated />
//using System;
//using HireMeNow.Models;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
=======
﻿// <auto-generated />
using System;
using JobPortalMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//#nullable disable

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//namespace HireMeNow.Migrations
//{
//    [DbContext(typeof(AppDbContext))]
//    [Migration("20250316214041_initial")]
//    partial class initial
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.3")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);
=======
namespace JobPortalMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250815180828_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Application", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Property<DateTime?>("AppliedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<Guid?>("CompanyId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<Guid?>("JobId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Status")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid?>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("Id");

//                    b.HasIndex("CompanyId");

//                    b.HasIndex("JobId");

//                    b.HasIndex("UserId");

//                    b.ToTable("Applications");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Company", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Property<string>("About")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Address")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("CreatedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Location")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<byte[]>("Logo")
//                        .HasColumnType("varbinary(max)");

//                    b.Property<string>("Mission")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Phone")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Status")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Vision")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Website")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Companies");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Experience", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Property<string>("Company")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Duration")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("JobTitle")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid?>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Year")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("Experiences");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Interview", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Property<Guid?>("CompanyId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime?>("CreatedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime?>("Date")
//                        .HasColumnType("datetime2");

//                    b.Property<Guid?>("JobId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Location")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Status")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<TimeSpan?>("Time")
//                        .HasColumnType("time");

//                    b.Property<Guid?>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<Guid?>("UserId1")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("Id");

//                    b.HasIndex("CompanyId");

//                    b.HasIndex("JobId");

//                    b.HasIndex("UserId");

//                    b.HasIndex("UserId1");

//                    b.ToTable("Interviews");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Job", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Property<int?>("AppliedCount")
//                        .HasColumnType("int");

//                    b.Property<Guid?>("CompanyId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<Guid?>("CreatedBy")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime?>("CreatedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Description")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Experience")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("JobType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Location")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Responsibilities")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Salary")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Status")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("TypeOfWorkPlace")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("UpdatedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("VacanciesCount")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("CompanyId");

//                    b.HasIndex("CreatedBy");

//                    b.ToTable("Jobs");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Qualification", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Property<string>("Mark")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Status")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("University")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("YearOfPassout")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("Qualifications");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Skill", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Property<string>("Status")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("Skills");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.User", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");
=======
            modelBuilder.Entity("JobPortalMVC.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Property<string>("About")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid?>("CompanyId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime?>("CreatedDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Designation")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("FirstName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Gender")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<byte[]>("Image")
//                        .HasColumnType("varbinary(max)");

//                    b.Property<string>("LastName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Location")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Phone")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int?>("Role")
//                        .HasColumnType("int");

//                    b.Property<string>("Status")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("password")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("CompanyId");

//                    b.ToTable("Users");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Application", b =>
//                {
//                    b.HasOne("HireMeNow.Models.Company", "Company")
//                        .WithMany()
//                        .HasForeignKey("CompanyId");

//                    b.HasOne("HireMeNow.Models.Job", "Job")
//                        .WithMany("Applications")
//                        .HasForeignKey("JobId");

//                    b.HasOne("HireMeNow.Models.User", "User")
//                        .WithMany("Applications")
//                        .HasForeignKey("UserId");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Application", b =>
                {
                    b.HasOne("JobPortalMVC.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("JobPortalMVC.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId");

                    b.HasOne("JobPortalMVC.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("Company");

//                    b.Navigation("Job");

//                    b.Navigation("User");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Experience", b =>
//                {
//                    b.HasOne("HireMeNow.Models.User", "User")
//                        .WithMany("Experiences")
//                        .HasForeignKey("UserId");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Experience", b =>
                {
                    b.HasOne("JobPortalMVC.Models.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("User");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Interview", b =>
//                {
//                    b.HasOne("HireMeNow.Models.Company", "Company")
//                        .WithMany()
//                        .HasForeignKey("CompanyId");

//                    b.HasOne("HireMeNow.Models.Job", "Job")
//                        .WithMany("Interviews")
//                        .HasForeignKey("JobId");

//                    b.HasOne("HireMeNow.Models.User", null)
//                        .WithMany("InterviewCreatedByNavigations")
//                        .HasForeignKey("UserId");

//                    b.HasOne("HireMeNow.Models.User", null)
//                        .WithMany("InterviewJobseekers")
//                        .HasForeignKey("UserId1");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Interview", b =>
                {
                    b.HasOne("JobPortalMVC.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("JobPortalMVC.Models.Job", "Job")
                        .WithMany("Interviews")
                        .HasForeignKey("JobId");

                    b.HasOne("JobPortalMVC.Models.User", null)
                        .WithMany("InterviewCreatedByNavigations")
                        .HasForeignKey("UserId");

                    b.HasOne("JobPortalMVC.Models.User", null)
                        .WithMany("InterviewJobseekers")
                        .HasForeignKey("UserId1");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("Company");

//                    b.Navigation("Job");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Job", b =>
//                {
//                    b.HasOne("HireMeNow.Models.Company", "Company")
//                        .WithMany("Jobs")
//                        .HasForeignKey("CompanyId");

//                    b.HasOne("HireMeNow.Models.User", "CreatedUser")
//                        .WithMany("Jobs")
//                        .HasForeignKey("CreatedBy");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Job", b =>
                {
                    b.HasOne("JobPortalMVC.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId");

                    b.HasOne("JobPortalMVC.Models.User", "CreatedUser")
                        .WithMany("Jobs")
                        .HasForeignKey("CreatedBy");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("Company");

//                    b.Navigation("CreatedUser");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Qualification", b =>
//                {
//                    b.HasOne("HireMeNow.Models.User", "User")
//                        .WithMany("Qualifications")
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
=======
            modelBuilder.Entity("JobPortalMVC.Models.Qualification", b =>
                {
                    b.HasOne("JobPortalMVC.Models.User", "User")
                        .WithMany("Qualifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("User");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Skill", b =>
//                {
//                    b.HasOne("HireMeNow.Models.User", "User")
//                        .WithMany("Skills")
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
=======
            modelBuilder.Entity("JobPortalMVC.Models.Skill", b =>
                {
                    b.HasOne("JobPortalMVC.Models.User", "User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("User");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.User", b =>
//                {
//                    b.HasOne("HireMeNow.Models.Company", "Company")
//                        .WithMany("Users")
//                        .HasForeignKey("CompanyId");
=======
            modelBuilder.Entity("JobPortalMVC.Models.User", b =>
                {
                    b.HasOne("JobPortalMVC.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("Company");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Company", b =>
//                {
//                    b.Navigation("Jobs");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Company", b =>
                {
                    b.Navigation("Jobs");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("Users");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.Job", b =>
//                {
//                    b.Navigation("Applications");
=======
            modelBuilder.Entity("JobPortalMVC.Models.Job", b =>
                {
                    b.Navigation("Applications");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("Interviews");
//                });

<<<<<<< HEAD:.netCore/MVC/WorkShop/HireMeNow/HireMeNow/Migrations/20250316214041_initial.Designer.cs
//            modelBuilder.Entity("HireMeNow.Models.User", b =>
//                {
//                    b.Navigation("Applications");
=======
            modelBuilder.Entity("JobPortalMVC.Models.User", b =>
                {
                    b.Navigation("Applications");
>>>>>>> 3620074c8308f0d6670ac2d226b0a3da63fa7b05:.netCore/MVC/Husna/Workshop/JobPortalMVC/Migrations/20250815180828_init.Designer.cs

//                    b.Navigation("Experiences");

//                    b.Navigation("InterviewCreatedByNavigations");

//                    b.Navigation("InterviewJobseekers");

//                    b.Navigation("Jobs");

//                    b.Navigation("Qualifications");

//                    b.Navigation("Skills");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
