create database UNIVERSITY_INFORMATION

CREATE TABLE UNIVERSITYSYSTEM
(
UID INT PRIMARY KEY,
NAME VARCHAR(20),
CHANCELLOR VARCHAR(20)
);
SELECT * FROM UNIVERSITYSYSTEM;

INSERT INTO UNIVERSITYSYSTEM (UID, NAME, CHANCELLOR)
VALUES (1, 'GLOBALTECH ', 'RENUKA SHARMA');

INSERT INTO UNIVERSITYSYSTEM (UID, NAME, CHANCELLOR)
VALUES (2, 'INFOTECH ', 'RENUKA SHARMA');




CREATE TABLE COLLEGE
(
CID INT PRIMARY KEY,
UNIVERSITY INT,
DEAN INT,
NAME VARCHAR(20),
FOREIGN KEY (UNIVERSITY) REFERENCES UNIVERSITYSYSTEM(UID),
 

);


SELECT * FROM COLLEGE;

CREATE TABLE DEAN
(
DEANID INT PRIMARY KEY ,
NAME VARCHAR(20),
DATEOFBIRTH DATETIME ,
);


select * from dean;



CREATE TABLE DEPATMENT
(
DID INT PRIMARY KEY,
COLLEGE INT ,
NAME VARCHAR(20),
FOREIGN KEY (COLLEGE) REFERENCES COLLEGE(CID),

);

select * from DEPATMENT;


CREATE TABLE PROFESSOR
(
PID INT PRIMARY KEY,
DEPARTMENT INT,
NAME VARCHAR(20),

FOREIGN KEY (DEPARTMENT) REFERENCES DEPATMENT(DID)
);

SELECT * FROM PROFESSOR;

CREATE TABLE COURSE
(
COURSEID INT PRIMARY KEY,
DEPARTMENT INT ,
NAME VARCHAR(20),
FOREIGN KEY (DEPARTMENT) REFERENCES DEPATMENT(DID)
);

SELECT * FROM COURSE;




CREATE TABLE SUBJECT
(
SUBJECTID INT PRIMARY KEY,
COURSE INT,
PROFESSOR INT,
NAME VARCHAR(20),
FOREIGN KEY (COURSE) REFERENCES COURSE(COURSEID),
FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR(PID),
);
SELECT * FROM SUBJECT;

CREATE TABLE STUDENT
(
STUDENTID INT PRIMARY KEY,
DEPARTMENT INT,
NAME VARCHAR(20),
DATEODENROLLMENT smalldatetime,
TELEPHONENUMBER VARCHAR(20),

FOREIGN KEY (DEPARTMENT) REFERENCES DEPATMENT(DID),

);

SELECT * FROM STUDENT;



CREATE TABLE STUDENT_REGISTRATION
(
STUDENT INT,
SUBJECT INT,
FOREIGN KEY (STUDENT) REFERENCES STUDENT(STUDENTID),
FOREIGN KEY (SUBJECT) REFERENCES SUBJECT(SUBJECTID),
);

SELECT * FROM STUDENT_REGISTRATION;