CREATE DATABASE EMPLOYEEDETAILS
CREATE TABLE  EMPLOYEE
(
 EMPLOYEEID INT PRIMARY KEY,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR (50),
DEPARTMENT VARCHAR(50),
HIREDATE DATE,


);
SELECT * FROM EMPLOYEE;
ALTER TABLE EMPLOYEE
ADD SALARY DECIMAL;

SELECT * FROM EMPLOYEE;
ALTER TABLE EMPLOYEE
DROP COLUMN HIREDATE;
SELECT * FROM EMPLOYEE;

CREATE TABLE DEPARTMENTS
(
DEPTID INT PRIMARY KEY,
DEPTNAME VARCHAR(50),
);

SELECT * FROM DEPARTMENTS;

DROP TABLE Departments;
INSERT INTO Employee (EmployeeID, FirstName, LastName, DepARTMENT, Salary,DEPTID)
VALUES
(1, 'Alice', 'Smith', 'Sales', 55000,2),
(2, 'Bob', 'Johnson', 'IT', 70000,3),
(3, 'Charlie', 'Brown', 'Marketing', 45000,5),
(4, 'David', 'Wilson', 'Sales', 28000,6),
(5, 'John', 'Doe', 'Finance', 50000,7);