create database CustomerOrder

create table customers
(
CUSTOMERID INT PRIMARY KEY,
CUSTOMERNAME VARCHAR(50),
CITY VARCHAR(100),
);

INSERT INTO customers(CUSTOMERID ,CUSTOMERNAME, CITY)
VALUES (1,'Alice','NewYork'),
(2,'Bob','Chicago'),
(3,'Charlie','Los Angles'),
(4,'David','houston');

select * from customers;

create table Orders
(
ORDERID INT PRIMARY KEY,
CUSTOMERID INT,
ORDERDATE DATE,
TOTALAMOUNT INT ,
FOREIGN KEY (CUSTOMERID) REFERENCES customers(CUSTOMERID)
);

INSERT INTO Orders(ORDERID ,CUSTOMERID, ORDERDATE,TOTALAMOUNT)
VALUES (101,1,'2024-02-15',500),
(102,2,'2024-02-16',700),
(103,1,'2024-03-01',200),
(104,3,'2024-03-05',900),
(105,2,'2024-03-07',450);

SELECT * FROM ORDERS


--TOTAL AMOUNT--

SELECT C.CUSTOMERNAME,SUM(O.TOTALAMOUNT) AS TOTALAMOUNTSPENT
FROM customers C
JOIN Orders O ON C.CUSTOMERID= O.CUSTOMERID
GROUP BY C.CUSTOMERNAME;


--NEVER PLACED ORDER--

SELECT C.CUSTOMERNAME AS NoOrderPlaced
FROM customers C
LEFT JOIN Orders O ON C.CUSTOMERID= O.CUSTOMERID
WHERE O.ORDERID IS NULL;


--MOST RECENT ORDER--
SELECT  C.CUSTOMERNAME ,MAX(O.ORDERDATE) AS RECENTORDER
FROM customers C
 JOIN Orders O ON C.CUSTOMERID= O.CUSTOMERID
 GROUP BY C.CUSTOMERNAME;



 --HIGHEST TOTALAMOUNT--

 SELECT C.CUSTOMERNAME,SUM(O.TOTALAMOUNT) HIGHESTSPENT
FROM customers C
JOIN Orders O ON C.CUSTOMERID= O.CUSTOMERID
GROUP BY C.CUSTOMERNAME
ORDER BY  HIGHESTSPENT DESC;


-- NUMBER OF ORDERS IN MARCH--

SELECT COUNT (*) AS ORDERMARCH
FROM ORDERS O
WHERE MONTH(ORDERDATE)=3;





