CREATE DATABASE Product_Details;
CREATE TABLE Product(
ProductID INT PRIMARY KEY,
ProductName VARCHAR(20),
Price DECIMAL(10,2)
);

CREATE TABLE Sales(
SaleID INT PRIMARY KEY,
ProductID INT, 
Quantity INT,
SaleDate DATE,
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);

INSERT INTO Product(ProductID,ProductName,Price) VALUES
(1,'Laptop',50000),

(2,'SmartPhone',25000),
(3,'Tablet',30000),
(4,'Smartwatch',10000);

INSERT INTO Sales(SaleID,ProductID,Quantity,SaleDate) VALUES
(101,1,3,'2024-03-01'),
(102,2,5,'2024-03-02'),
(103,1,2,'2024-03-05'),
(104,3,1,'2024-03-06'),
(105,2,3,'2024-03-07');

SELECT * FROM Product;
SELECT * FROM Sales;


--Write a SQL query to find the total revenue generated by each product.
SELECT Product.ProductID,
Product.ProductName,
SUM(Product.Price*Sales.Quantity) AS TotalRevenue
FROM Product
JOIN Sales ON Product.ProductID=Sales.ProductID
GROUP BY Product.ProductID,Product.ProductName

--Write a SQL query to find the best-selling product based on quantity sold.

SELECT Product.ProductID,
Product.ProductName,
SUM(Sales.Quantity) AS TotalQuantitySold
FROM Product
JOIN Sales ON Product.ProductID=Sales.ProductID
GROUP BY Product.ProductID,Product.ProductName
ORDER BY 
TotalQuantitySold DESC;

--Write a SQL query to find the product(s) that have never been sold.
SELECT Product.ProductID,
Product.ProductName
FROM
Product
LEFT JOIN Sales ON Product.ProductID=Sales.ProductID
WHERE Sales.ProductID IS NULL;

--Write a SQL query to find the total revenue generated in the month of March 2024.

SELECT SUM(Product.Price*Sales.Quantity) AS TotalRevenue
FROM
Product
JOIN
Sales ON Product.ProductID=Sales.ProductID












